pipeline {
    agent any
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                echo 'Build'
            }
        }
        stage('Test') {
            steps {
                echo 'Test'
            }
        }
        stage('Deliver for development') {
            when {
                branch 'development'
            }
            steps {
               echo 'Deliver for development'
            }
        }
        stage('Deploy for production') {
            when {
                branch 'production'
            }
            steps {
               echo 'Deploy for production'
            }
        }
    }
}
